apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-j4ir
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-j4ir
    app.kubernetes.io/part-of: test-app-876
  name: maven-hello-world-j4ir
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-j4ir
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-j4ir
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-876/maven-hello-world-j4ir@sha256:a7d02bdf1e219ce560887a31568d1d1f2cf361f3777d720aaed63a90e5cdbc7c
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
