apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-sample-repo-obe3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-sample-repo-obe3
    app.kubernetes.io/part-of: test-app-876
  name: fbc-sample-repo-obe3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-sample-repo-obe3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-sample-repo-obe3
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-876/fbc-sample-repo-obe3@sha256:97ff4e72759f2abdbeb8d8b18daa836b386c858761e5e9edc29278fbf1c806e7
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
