apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-uk8m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-uk8m
    app.kubernetes.io/part-of: test-app-876
  name: nodejs-no-dockerfile-uk8m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-uk8m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-uk8m
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-876/nodejs-no-dockerfile-uk8m@sha256:ec9f34437acbd21a1e30c935d2096ecbad8d9fb0b4c13577e86a7f867aaaa1b9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
